create table public.products (
  id uuid primary key default gen_random_uuid(),
  gtin text not null unique,
  product_name text not null,
  brand_name text,
  manufacturer text,
  manufacturer_address text,
  packer text,
  packer_address text,
  marketer text,
  marketer_address text,
  importer text,
  importer_address text,
  net_quantity numeric,
  unit text,
  mrp numeric,
  currency text not null default 'INR',
  date_of_manufacture text,
  date_of_packing text,
  best_before text,
  expiry_date text,
  batch_number text,
  consumer_care_phone text,
  consumer_care_email text,
  country_of_origin text,
  fssai_license_number text,
  barcode text,
  product_category text,
  product_subcategory text,
  description text,
  image_url text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
